# Generated by Django 5.1.7 on 2025-04-08 19:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
