# Generated by Django 5.1.7 on 2025-04-21 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blog_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL, verbose_name='No me Gusta'),
        ),
    ]
