# Generated by Django 5.1.7 on 2025-05-10 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_blog_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
