# Generated by Django 5.1.7 on 2025-05-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_rename_descripcion_blog_contenido_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-date_created']},
        ),
    ]
