# Generated by Django 5.1.7 on 2025-05-11 00:32

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_blog_options_alter_comentario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Post_tag',
        ),
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('imagen_portada', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='Blog.post_tag')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Post_comment',
            fields=[
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_post')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Reaction_post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='dislike_post', to=settings.AUTH_USER_MODEL, verbose_name='No me Gusta')),
                ('likes', models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='Me Gusta')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='post_reactions',
            field=models.ManyToManyField(to='Blog.reaction_post'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
