# Generated by Django 5.1.7 on 2025-05-11 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_remove_comentario_blog_remove_comentario_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='post_reactions',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislike_post', to=settings.AUTH_USER_MODEL, verbose_name='No me Gusta'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='Me Gusta'),
        ),
        migrations.DeleteModel(
            name='Reaction_post',
        ),
    ]
