# Generated by Django 5.1.7 on 2025-05-11 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_remove_blog_post_post_reactions_blog_post_dislikes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_postss', to=settings.AUTH_USER_MODEL, verbose_name='No me Gusta'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Me Gusta'),
        ),
    ]
