# Generated by Django 5.1.7 on 2025-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_alter_blog_post_dislikes_alter_blog_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_tag',
            options={'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='post_tag',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
