# Generated by Django 5.1.7 on 2025-05-11 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_alter_post_tag_options_post_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='tags',
            field=models.ManyToManyField(to='Blog.post_tag'),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_post'),
        ),
    ]
