# Generated by Django 5.1.7 on 2025-05-17 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_blog_post_tags_alter_post_comment_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Reaction_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.ManyToManyField(related_name='blog_postss', to=settings.AUTH_USER_MODEL, verbose_name='No me Gusta')),
                ('likes', models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Me Gusta')),
            ],
        ),
    ]
