# Generated by Django 5.1.7 on 2025-05-18 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_remove_blog_post_dislikes_remove_blog_post_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_postss', to=settings.AUTH_USER_MODEL, verbose_name='No me Gusta'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Me Gusta'),
        ),
        migrations.DeleteModel(
            name='Reaction_post',
        ),
    ]
