# Generated by Django 5.1.7 on 2025-05-26 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_blog_post_dislikes_blog_post_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Reation_Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='blog_postss', to=settings.AUTH_USER_MODEL, verbose_name='No me Gusta')),
                ('likes', models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Me Gusta')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='reaction',
            field=models.ManyToManyField(to='Blog.reation_posts'),
        ),
    ]
