# Generated by Django 5.1.7 on 2025-05-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_remove_blog_post_dislikes_remove_blog_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='reaction',
        ),
        migrations.AddField(
            model_name='reation_posts',
            name='blog',
            field=models.ManyToManyField(related_name='blog', to='Blog.blog_post', verbose_name='blog'),
        ),
    ]
