# Generated by Django 5.1.7 on 2025-05-26 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_remove_blog_post_reaction_reation_posts_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reation_Posts',
            new_name='Reaction_Posts',
        ),
    ]
