# Generated by Django 5.1.7 on 2025-05-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_rename_reation_posts_reaction_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction_posts',
            name='blog',
        ),
        migrations.AddField(
            model_name='reaction_posts',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Blog.blog_post'),
            preserve_default=False,
        ),
    ]
