# Generated by Django 5.1.7 on 2025-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_remove_reaction_posts_blog_reaction_posts_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='id',
            new_name='blog_id',
        ),
        migrations.RenameField(
            model_name='post_comment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='post_tag',
            old_name='id',
            new_name='tag_id',
        ),
        migrations.RenameField(
            model_name='reaction_posts',
            old_name='id',
            new_name='Reaction_id',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='tags',
            field=models.ManyToManyField(related_name='blog_tag', to='Blog.post_tag'),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
